variables:
  TZN_CONFIGFILE: "gitlab.config"
  
include:
  - project: 'tommzn-solutions-dev/devops/ci-template'
    ref: master
    file: '/golang/tests_with_local_dynamodb.yml'
  - project: 'tommzn-solutions-dev/devops/ci-template'
    ref: master
    file: '/release/semantic-version.yml'
    
stages:
  - test
  - release