variables:
  TZN_CONFIGFILE: "gitlab.config"
  GITHUB_REPO: "git@gitlab.com:tommzn-ext/github.com/recipeboard-core.git"
  
include:
  - project: 'tommzn-solutions-dev/devops/ci-template'
    ref: master
    file: '/golang/tests_with_local_dynamodb.yml'
  - project: 'tommzn-solutions-dev/devops/ci-template'
    ref: master
    file: '/release/semantic-version.yml'
  - project: 'tommzn-solutions-dev/devops/ci-template'
    ref: master
    file: '/release/push_tags_to_github.yml'
    
stages:
  - test
  - release
  - publish