
log:
  type: local
  loglevel: debug
  namespace: recipeboard-core-test
  batchsize: 5
  
aws:
  dynamodb:
    region: eu-west-5
    tablename: DynamoDbTestTable
    endpoint: http://localhost:8000
  sqs:
    region: eu-central-1
    queue: tzn-unittest
