
log:
  type: local
  loglevel: debug
  namespace: recipeboard-core-test
  batchsize: 5
  
aws:
  dynamodb:
    awsregion: eu-west-5
    tablename: DynamoDbTestTable
    endpoint: http://localhost:8000
